booking/urls.py
from django.urls import path
from .views import main, auth, host, guest, stripe
from django.conf import settings
from django.conf.urls.static import static
from .views import main, auth, host, guest


urlpatterns = [
    #main.py
    path('', main.index.as_view(), name='index'),
    #auth.py
    path('host/signup/', auth.signup_host.as_view(), name='signup_host'),
    path('signup/', auth.signup_guest.as_view(), name='signup_guest'),
    path('login/', auth.login_common.as_view(), name='login'),
    path('logout/', auth.logout_common.as_view(), name='logout'),

    #host.py
    path('host', host.host_index.as_view(), name='host_index'),                                     #TODO
    path('host/facility/register', host.facility_register.as_view(), name='facility_register'),     #TODO
    path('host/room/register', host.room_register.as_view(), name='room_register'),                 #TODO
    path('host/event/register', host.event_register.as_view(), name='event_register'),              #TODO

    #guest.py
    path('mypage/', guest.guest_mypage.as_view(), name='guest_mypage'),
    path('facility/index/', guest.facility_index.as_view(), name='facility_index'),
    path('facility/<uuid:facility_id>/', guest.facility_detail.as_view(), name='facility_detail'),
    path('reserve/<uuid:selected_facility_id>/frame/index', guest.reserve_frame_index.as_view(), name='reserve_frame_index'),
    path('reserve/<uuid:selected_facility_id>/<int:selected_frame_id>/', guest.reserve_frame_apply.as_view(), name='reserve_frame_apply'),
    path('reserve/save/', guest.reserve_save.as_view(), name='reserve_save'),
    path('facility/event/apply/save', guest.guest_event_apply_save.as_view(), name='event_apply_save'),
    path('facility/event/apply/<uuid:facility_uid>/<int:event_id>', guest.guest_event_apply.as_view(), name='event_apply'),

    #stripe.py
    path("stripe", stripe.ProductTopPageView.as_view(), name="product-top-page"),   
    path("create-checkout-session/<pk>/", stripe.CreateCheckoutSessionView.as_view(), name="create-checkout-session"),    # 個別商品決済画面
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

guesthouse/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('booking.urls')),
]

booking/models.py
import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser
import uuid


class CommonUser(AbstractUser):
    uid = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    birth_date = models.DateField()

    REQUIRED_FIELDS = ['uid', 'birth_date']

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = ('CommonUser')


class HostUser(CommonUser):
    def __str__(self):
        return self.username

    class Meta:
        verbose_name = ('HostUser')


class GuestUser(CommonUser):
    def __str__(self):
        return self.username

    class Meta:
        verbose_name = ('GuestUser')


class Facility(models.Model):
    uid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100)
    post_code = models.CharField(max_length=7)
    address = models.CharField(max_length=200)
    photo = models.ImageField(upload_to='images/', null=True)
    bio = models.CharField(max_length=400, blank=True)
    website = models.URLField(blank=True)
    host = models.ForeignKey(to=HostUser, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.name


class Event(models.Model):
    event_name = models.CharField(max_length=100)    #後でnameに変更
    event_detail = models.CharField(max_length=1000)
    facility = models.ForeignKey(to=Facility, on_delete=models.CASCADE)
    host = models.ForeignKey(to=HostUser, on_delete=models.DO_NOTHING)
    begin_date = models.DateField()
    end_date = models.DateField()
    deadline = models.DateField()
    max_participants = models.IntegerField()
    current_participants = models.IntegerField(default=0)
    def __str__(self):
        return self.facility.name + '_' + self.event_name

class EventApplication(models.Model):
    event = models.ForeignKey(to=Event, on_delete=models.CASCADE)
    guestuser = models.ForeignKey(to=GuestUser, on_delete=models.CASCADE)
    is_present = models.BooleanField(default=False)
    comment = models.CharField(max_length=1000)
    def __str__(self):
        return str(self.date) + '_' + self.event.facility.name + '_' + self.event.event_name


class Room(models.Model):
    room_name = models.CharField(max_length=100)    #後でnameに変更
    facility = models.ForeignKey(to=Facility, on_delete=models.CASCADE)

    def __str__(self):
        return self.facility.name + '_' + self.room_name

class ReservationFrame(models.Model):
    date = models.DateField()
    is_reserved = models.BooleanField(default=False)
    room = models.ForeignKey(to=Room, on_delete=models.SET_NULL, null=True)
    stripe_product_id = models.CharField(max_length=100, default='prod_Nb1gCAxVrlgwRv')

    def __str__(self):
        return str(self.date) + '_' + self.room.facility.name + '_' + self.room.room_name

class Price(models.Model):
    # 外部キーで商品マスタを紐付け
    product = models.ForeignKey(ReservationFrame, related_name='Prices', on_delete=models.CASCADE)
    # 価格ID（★stripeの価格IDを値に用いる）
    stripe_price_id = models.CharField(max_length=100)
    # 価格
    price = models.IntegerField(default=0)
    
    # Django画面に表示する価格
    def get_display_price(self):
        return self.price

class Reservation(models.Model):
    is_canceled = models.BooleanField(default=False)
    is_checked_in = models.BooleanField(default=False)
    check_in_date = models.DateField()
    check_out_date = models.DateField()
    guest = models.ForeignKey(to=GuestUser, on_delete=models.SET_NULL, null=True)   #たぶんnullじゃよくない
    room = models.ForeignKey(to=Room, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return str(self.check_in_date) + '_' + self.room.facility.name + '_' + self.guest.username

booking/views/guest.py
from django.http import HttpResponse, Http404
from django.views.generic import View
from django.shortcuts import render, redirect
from booking.forms import auth
from ..models import Facility, Reservation, ReservationFrame, Room, Event, EventApplication
import datetime
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from ..decorators import guest_login_required
from django.utils.decorators import method_decorator

class guest_mypage(View):
    @method_decorator(guest_login_required)
    def get(self, request):
        current_guest_id = request.user.guestuser.uid
        reservations = Reservation.objects.filter(guest_id = current_guest_id).order_by('check_in_date')
        event_applications_list = EventApplication.objects.filter(guestuser_id = current_guest_id).distinct().values_list('event', flat = True)
        events = Event.objects.filter(pk__in = event_applications_list)
        param={
            'reservations':reservations,
            'events':events
        }
        return render(request, "booking/guest/mypage.html", param)

class facility_index(View):
    @method_decorator(login_required)
    def get(self, request):
        Facility_list = Facility.objects.order_by('name')
        param = {
            'Facility_list':Facility_list,
            'words' : ' ', 
            'places' : ' ', 
            'selected_checkin' : datetime.datetime.now().date().isoformat(),
            'selected_checkout' : datetime.datetime.now().date().isoformat(),
        }
        return render(request, "booking/guest/facility_index.html", param)
        #return HttpResponse("You're looking at facility_index")
    
    @method_decorator(guest_login_required)
    def post(self, request):
        #検索文字列POST["words"]の全角スペースを半角スペースに変換し、半角スペースで区切る。区切った各ワードを配列wordsに格納
        words = request.POST["words"].replace("　"," ").split(" ")
        places = request.POST["places"].replace("　"," ").split(" ")


        #配列wordsの各要素wordでand検索をかける
        searched_facility_list = Facility.objects
        for word in words:
            searched_facility_list = searched_facility_list.filter(name__icontains = word)

        #placeでのor検索
        q = Q()
        for place in places:
            q.add(Q(address__icontains =place), Q.OR)
        searched_facility_list = searched_facility_list.filter(q)

        selected_checkin = datetime.datetime.strptime(request.POST["checkin"], "%Y-%m-%d").date()
        selected_checkout = datetime.datetime.strptime(request.POST["checkout"], "%Y-%m-%d").date()
        
        
        #is_date_searchがtrueのとき、checkinからcheckoutまでの日程が確保できる施設のみを検索
        if request.POST["is_date_search"] == "1":
            #チェックイン日付がチェックアウト日付より後の場合は初期値を空にしてからの絞り込み = 施設を表示しない
            if selected_checkin > selected_checkout:
                available_facilities_name = []
            else:
                #予約可能な施設の初期値は全施設 = 全集合からの絞り込みによって正常に検索を行う
                available_facilities_name = list(Facility.objects.all().distinct().values_list("name", flat=True))

            for i in range(( selected_checkout - selected_checkin).days + 1): #日付についてfor文を回す
                currentdate = selected_checkin + datetime.timedelta(i)

                #currentdateに対して空いている予約枠を取得
                current_available_frames = ReservationFrame.objects.filter(is_reserved = 0).filter(date = currentdate).order_by("date")

                #currentdateに対して空いている予約枠に属するfacilityを全て取得、施設名をcurrent_available_facilities_nameに格納
                current_available_facilities_name = []
                for current_available_frame in current_available_frames:
                    current_available_facilities_name.append(current_available_frame.room.facility.name)

                #currentdateに対して空きのある施設のみに絞り込んでいく
                available_facilities_name= list(set(available_facilities_name) & set(current_available_facilities_name)) 

            #検索結果を予約枠に空きがある施設のみに限定
            searched_facility_list = searched_facility_list.filter(name__in = available_facilities_name)
        
        #nameで並び替え
        searched_facility_list = searched_facility_list.order_by('name')
        words = ' '.join(map(str, words))
        places = ' '.join(map(str, places))
        param = {
            'Facility_list':searched_facility_list,
            'words': words, 
            'places': places, 
            'selected_checkin': selected_checkin.isoformat(),
            'selected_checkout':selected_checkout.isoformat(), 
        }
        return render(request, "booking/guest/facility_index.html", param)

class facility_detail(View):
    @method_decorator(guest_login_required)
    def get(self, request, facility_id):
        #return HttpResponse("You're looking at facility_detail")
        try:
            facility = Facility.objects.get(pk=facility_id)
            events = Event.objects.filter(facility=facility)
        except facility.DoesNotExist:
            raise Http404("Facility does not exist")
        return render(request, 'booking/guest/facility_detail.html', {'facility': facility, 'events' : events})
    
class reserve_frame_index(View):
    @method_decorator(guest_login_required)
    def get(self, request, selected_facility_id):
        try:
            selected_facility = Facility.objects.get(pk=selected_facility_id)
            rooms = Room.objects.filter(facility_id=selected_facility_id)
            reservation_frames = ReservationFrame.objects.filter(is_reserved = 0).filter(room_id__in = rooms).order_by("date")
            available_date_lists = list(reservation_frames.distinct().values_list('date', flat = True))
            
            #capacity_listはavailable_date_listsとkeyが対応しており、その日付における空き部屋の数を格納している
            capacity_list = []
            for available_date in available_date_lists:
                capacity_list.append(reservation_frames.filter(date = available_date).count())

            #available_date_listsとcapacity_listを結合する。一応対応する予約枠のidもつけておく(実装に応じて要変更)
            available_frames = []
            for i in range(len(capacity_list)):
                first_frame = ReservationFrame.objects.filter(is_reserved = 0).filter(room_id__in = rooms).filter(date = available_date_lists[i]).order_by("room_id").first()
                available_frames.append({"date":available_date_lists[i],"number":capacity_list[i], \
                                         "first_frame_id":first_frame.id})

            
            param = {
                'facility':selected_facility,
                'capacity_list': capacity_list,
                'available_frames': available_frames,
            }
        except selected_facility.DoesNotExist:
            raise Http404("Facility does not exist")
        return render(request, "booking/guest/reserve_frame.html", param)

#チェックイン先のfacilityとチェックイン日付(リンク生成の都合上reservation_frameで渡している)が与えられたとき、チェックアウト可能な最も遅い日付をdeadlineに格納する。
#チェックアウト可能な最も遅い日付 == チェックイン日付から、利用可能なreservation_frameが連続的に確保できる日付
#while文を与えているので、雑に編集すると無限ループの可能性があるので注意。
class reserve_frame_apply(View):
    @method_decorator(guest_login_required)
    def get(self, request, selected_facility_id, selected_frame_id):
        if ReservationFrame.objects.filter(is_reserved = 0).filter(pk=selected_frame_id).exists():
            selected_reservation = ReservationFrame.objects.filter(is_reserved = 0).filter(pk=selected_frame_id).get()
            deadline = ReservationFrame.objects.filter(is_reserved = 0).filter(pk=selected_frame_id).first().date
            rooms = Room.objects.filter(facility_id=selected_facility_id)
            while ReservationFrame.objects.filter(is_reserved = 0).filter(room_id__in = rooms).filter(date__gt=deadline).exists():
                deadline = deadline + datetime.timedelta(days=1)
            param = {'selected_reservation': selected_reservation,
                     'facility' : Facility.objects.get(pk=selected_facility_id), 
                     'selected_date':selected_reservation.date.isoformat(), 
                     'deadline':deadline.isoformat()}
            return render(request, 'booking/guest/reserve_apply.html', param)
        else:
            return HttpResponse("空いている予約枠がありません。")

class reserve_save(View):
    @method_decorator(guest_login_required)
    def post(self, request):
        selected_guest_id = request.user.guestuser.uid
        selected_check_in_date = datetime.datetime.strptime(request.POST["checkin"], "%Y-%m-%d")
        selected_check_out_date = datetime.datetime.strptime(request.POST["checkout"], "%Y-%m-%d")
        rooms = Room.objects.filter(facility_id=request.POST["facility_uid"])
        selected_reservation = ReservationFrame.objects.filter(is_reserved=0).filter(room_id__in=rooms).filter(date=selected_check_in_date)\
            .order_by("room_id").first()
        selected_room_id = selected_reservation.room.id

        #保存処理を行う前に、日程が確保できているか一応確認する。selected_check_in_dateからselected_check_out_dateまで、その日付かつselected_roomに空きがあることを
        #確認し、空きがあれば{exists() == True}、変更対象のframeを格納する配列reserved_framesに追加し、一つでも空きがなければ予約失敗と表示する。
        #一つも予約枠確保が失敗しなかったときのみ保存処理を実行
        reserved_frames = []
        for i in range(( selected_check_out_date - selected_check_in_date).days + 1):
            currentdate = selected_check_in_date + datetime.timedelta(i)
            reserved_frame = ReservationFrame.objects.filter(is_reserved=0).filter(room_id=selected_room_id).filter(date=currentdate)
            if reserved_frame.exists():
                reserved_frames.append(reserved_frame)
            else:
                return HttpResponse("予約枠を確保できませんでした。再度お試しください。")
        for reserved_frame in reserved_frames:
            reserved_frame = reserved_frame.get()
            reserved_frame.is_reserved = 1
            reserved_frame.save()
        Reservation.objects.create(is_canceled = 0, is_checked_in = 0, check_in_date = selected_check_in_date, check_out_date = selected_check_out_date,\
                                room_id = selected_room_id, guest_id = selected_guest_id)

booking/views/stripe.py
import json
import stripe
from django.conf import settings
from django.http import JsonResponse, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.views import View
from django.shortcuts import redirect
from django.views.generic import ListView
from ..models import ReservationFrame
from ..models import Price

# STRIPEのシークレットキー
stripe.api_key = settings.STRIPE_SECRET_KEY

class ProductTopPageView(ListView):
    # 商品マスタ
    model = ReservationFrame
    # ページリンク
    template_name = "booking/stripe/product-top.html"
    #レコード情報をテンプレートに渡すオブジェクト
    context_object_name = "product_list"


class CreateCheckoutSessionView(View):

    def post(self, request, *args, **kwargs):
        # 商品マスタ呼出
        product = ReservationFrame.objects.get(id=self.kwargs["pk"])
        price   = Price.objects.get(product=product)

        # ドメイン
        YOUR_DOMAIN = "http://127.0.0.1:8000"
        # 決済用セッション
        checkout_session = stripe.checkout.Session.create(
            # 決済方法
            payment_method_types=['card'],
            # 決済詳細
            line_items=[
                {
                    'price': price.stripe_price_id,       # 価格IDを指定 
                    'quantity': 1,                        # 数量
                },
            ],
            # POSTリクエスト時にメタデータ取得
            metadata = {
                        "product_id":product.id,
                       },
            mode='payment',                               # 決済手段（一括）
            success_url=YOUR_DOMAIN + '/success/',        # 決済成功時のリダイレクト先
            cancel_url=YOUR_DOMAIN + '/cancel/',          # 決済キャンセル時のリダイレクト先
        )
        return redirect(checkout_session.url)

booking/templates/booking/host/event/register.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <script src="https://cdn.tailwindcss.com"></script>
        <link rel="icon" type="image/png" href="{% static 'booking/images/logo.png' %}"/>
        <title>Guest House App</title>
    </head>
    {% include "booking/nav_host.html" %}
    <body>
        <div class="mx-auto max-w-screen-x py-8">
            <div class="mx-auto max-w-lg text-center">
              <h1 class="text-2xl font-bold text-rose-900 sm:text-3xl">Event Register</h1>
            </div>
        
            <form action="{% url 'event_register' %}" method="post" class="mx-auto mt-8 mb-0 max-w-md space-y-4">
            {% csrf_token %}
        
                <!-- Event Name -->
                <div>
                    <label for="id_event_name">Event Name</label>
                    <div class="relative">
                        <input
                        class="w-full rounded-lg border-2 border-gray-200 p-4 pr-12 text-sm shadow-sm"
                        type="text" name="event_name" maxlength="100" required id="id_name"
                        placeholder="Enter event name"
                        />
                    </div>
                </div>

                <!-- Facility -->
                <label for="id_facility_name">Facility</label>
                {{ form.facility }}

                <!-- Event Detail -->
                <div>
                    <label for="id_event_detail">Event Detail</label>
                    <div class="relative">
                        <input
                        class="w-full rounded-lg border-2 border-gray-200 p-4 pr-12 text-sm shadow-sm"
                        type="text" name="event_detail" maxlength="1000" required id="id_event_detail"
                        placeholder="Enter address"
                        />
                    </div>
                </div>

                <!-- Date -->
                <div>
                    <label for="id_begin_date">Begin Date</label>
                    <div class="relative">
                        <input
                        class="w-full rounded-lg border-2 border-gray-200 p-4 pr-12 text-sm shadow-sm"
                        type="text" name="begin_date" required id="id_begin_date"
                        placeholder="Enter begin date"
                        />
                    </div>
                </div>
                
                <div>
                    <label for="id_end_date">End Date</label>
                    <div class="relative">
                        <input
                        class="w-full rounded-lg border-2 border-gray-200 p-4 pr-12 text-sm shadow-sm"
                        type="text" name="end_date" required id="id_end_date"
                        placeholder="Enter end date"
                        />
                    </div>
                </div>

                <div>
                    <label for="id_deadline">Deadline</label>
                    <div class="relative">
                        <input
                        class="w-full rounded-lg border-2 border-gray-200 p-4 pr-12 text-sm shadow-sm"
                        type="text" name="deadline" required id="id_deadline"
                        placeholder="Enter deadline"
                        />
                    </div>
                </div>

                <!-- Max Participants -->
                <div>
                    <label for="id_max_participants">Max Participants</label>
                    <div class="relative">
                        <input
                        class="w-full rounded-lg border-2 border-gray-200 p-4 pr-12 text-sm shadow-sm"
                        type="number" name="max_participants" required id="id_max_participants"
                        placeholder="Enter max participants"
                        />
                    </div>
                </div>

                <div class="flex justify-end">
                    <button
                      type="submit"
                      class="inline-block rounded-lg bg-rose-900 px-4 py-2 text-sm font-medium text-white"
                    >
                      Register
                    </button>
                </div>
            </form>
        
        </div>
    </body>
</html>